apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: combo
namePrefix: release-
resources:
  - ../../../postgres.yaml
  - ../../../redis-queue.yaml
  - ../../../redis-hot.yaml
  - ../../../minio.yaml
patches:
  - path: storage.patch.yaml
  - path: pull-secret.patch.yaml
  - target:
      kind: Service
      name: minio
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: remove
        path: /spec/ports/0/nodePort
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      combo.build/environment-foundation: production-v1
images:
  - name: postgres
    newName: postgres
    digest: sha256:7c688148e5e156d0e86df7ba8ae5a05a2386aaec1e2ad8e6d11bdf10504b1fb7
  - name: redis
    newName: redis
    digest: sha256:bb186d083732f669da90be8b0f975a37812b15e913465bb14d845db72a4e3e08
  - name: minio/minio
    newName: minio/minio
    digest: sha256:d249d1fb6966de4d8ad26c04754b545205ff15a62e4fd19ebd0f26fa5baacbc0
