apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          combo.build/data-policy: disposable
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-queue
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          combo.build/data-policy: disposable
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          combo.build/data-policy: disposable
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
