apiVersion: v1
kind: ResourceQuota
metadata:
  name: sandbox-capacity
  namespace: combo-sandbox
spec:
  hard:
    count/pods: '4'
    count/persistentvolumeclaims: '4'
    requests.storage: 4Gi
    requests.cpu: 400m
    requests.memory: 1536Mi
    requests.ephemeral-storage: 512Mi
    limits.cpu: '2'
    limits.memory: 1536Mi
    limits.ephemeral-storage: 512Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sandbox-container-bounds
  namespace: combo-sandbox
spec:
  limits:
    - type: Container
      max:
        cpu: 500m
        memory: 384Mi
        ephemeral-storage: 128Mi
      defaultRequest:
        cpu: 100m
        memory: 384Mi
        ephemeral-storage: 128Mi
      default:
        cpu: 500m
        memory: 384Mi
        ephemeral-storage: 128Mi
