packages:
  - 'packages/*'
  - 'apps/*'
  - 'db'
  - 'infra'
  - 'scripts'
allowBuilds:
  '@bundled-es-modules/glob': false
  '@google/genai': false
  esbuild: true
  msgpackr-extract: true
  protobufjs: false
  style-dictionary: false
