apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: combo-preview
resources:
  - resources.yaml
configMapGenerator:
  - name: combo-dev-nginx
    files:
      - default.conf.template=nginx-dev.conf
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      combo.dev/environment: combo-dev
