apiVersion: v1
kind: ResourceQuota
metadata:
  name: sandbox-capacity
  namespace: combo-sandbox
spec:
  hard:
    count/pods: '5'
    count/persistentvolumeclaims: '5'
    requests.storage: 5Gi
    requests.cpu: 500m
    requests.memory: 1920Mi
    requests.ephemeral-storage: 640Mi
    limits.cpu: 2500m
    limits.memory: 1920Mi
    limits.ephemeral-storage: 640Mi
