// Session noise predicates shared by import parsing and extract clustering.
// These strings are generated by coding-agent runtimes, not by the user task itself.

const PLATFORM_PROMPT_PREFIXES = [
  '<environment_context>',
  '# AGENTS.md instructions',
  '# Files mentioned by the user:',
  '<local-command-caveat>',
  'Generate a title and a git branch name for a coding agent from the user prompt',
  'You are editing a Markdown artifact for a local AI doc editor.',
];

export function firstNonEmptyLine(text: string | null | undefined): string {
  if (!text) return '';
  return (
    text
      .replace(/\r\n/g, '\n')
      .split('\n')
      .map((line) => line.trim())
      .find((line) => line.length > 0) ?? ''
  );
}

export function stripRolePrefix(line: string): string {
  return line.replace(/^(user|assistant|system|tool):\s*/i, '').trim();
}

export function isPlatformPromptText(text: string | null | undefined): boolean {
  const first = stripRolePrefix(firstNonEmptyLine(text));
  if (!first) return false;
  const lower = first.toLowerCase();
  return PLATFORM_PROMPT_PREFIXES.some((prefix) => lower.startsWith(prefix.toLowerCase()));
}

export function isBlockedCapabilityLabel(text: string | null | undefined): boolean {
  const first = firstNonEmptyLine(text);
  if (!first) return true;
  return isPlatformPromptText(first);
}
