apiVersion: v1
kind: ResourceQuota
metadata:
  name: combo-dev-ceiling
spec:
  hard:
    pods: '12'
    persistentvolumeclaims: '3'
    requests.cpu: 1500m
    limits.cpu: 3000m
    requests.memory: 4Gi
    limits.memory: 6Gi
    requests.ephemeral-storage: 4Gi
    limits.ephemeral-storage: 8Gi
    requests.storage: 16Gi
    combo-dev-bounded.storageclass.storage.k8s.io/requests.storage: 16Gi
