apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../api.yaml
  - ../../../worker.yaml
  - ../../../runtime.yaml
  - ../../../web.yaml
patches:
  - path: api-release.patch.yaml
  - path: worker-release.patch.yaml
  - path: runtime-release.patch.yaml
  - path: web-release.patch.yaml
  - target:
      kind: Service
      name: web
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: remove
        path: /spec/ports/0/nodePort
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      combo.build/managed-by: release-v1
images:
  - name: ghcr.io/dangdang-tech/combo-api
    newName: ghcr.io/dangdang-tech/combo-api
    digest: sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  - name: ghcr.io/dangdang-tech/combo-runtime
    newName: ghcr.io/dangdang-tech/combo-runtime
    digest: sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  - name: ghcr.io/dangdang-tech/combo-web
    newName: ghcr.io/dangdang-tech/combo-web
    digest: sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
