apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-queue
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-hot
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
